### ISSUE TITLE
Error: | UPDATING PRICES |: Couldn't price x. Issue with Price.tf.

### ISSUE THREAD

**Issue by LCJE** [jack-richards/bptf-autopricer#15]
After correctly installing, running and setting up tf2 autobot with this pricer, whenever it tries to price something it always gives this error, there seems to be nothing wrong with prices.tf at the momment so im left confused on why this is happening. Here is the full error

1|bptf-autopricer  | Error: | UPDATING PRICES |: Couldn't price Name Tag. Issue with Price.tf.
1|bptf-autopricer  |     at determinePrice (/home/user/autopricer/bptf-autopricer.js:501:15)
1|bptf-autopricer  |     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
1|bptf-autopricer  |     at async calculateAndEmitPrices (/home/user/autopricer/bptf-autopricer.js:198:23)
1|bptf-autopricer  |     at async Timeout._onTimeout (/home/user/autopricer/bptf-autopricer.js:352:9)
1|bptf-autopricer  | Couldn't create a price for Name Tag

**Comment by jack-richards** [comment]
Not sure what causes this issue as it never occurred in the past, indicating that it's not a problem with my code per se but probably the data it draws.

After messaging someone having this issue, It appears that the SKU generated from the Backpack.tf item name provided is sometimes wrong, though this is a rare occurrence. This prompted me to message the dev of the `@tf2autobot/tf2-schema` library, who confirmed that it had not been changed, which made the issue quite puzzling.

It's probably something to do with the tf2 schema fetched from Steam, however, I have not confirmed this. The person I was messaging found that the issue resolved itself after updating their packages and restarting the bot, I would recommend doing the same.

If I get some time I may try to diagnose what could be causing this more comprehensively.

**Comment by jack-richards** [comment]
This has received no further comments so I am closing this issue. After testing I have not run into the same issue, it might be a case of un-updated packages as I speculated.
