### ISSUE TITLE
Error occurred getting auth token from prices.tf, retrying...

### ISSUE THREAD

**Issue by Mo7TaRiF** [jack-richards/bptf-autopricer#8]
Hello,
I keep getting this messages and it has been a week since last update for items and also can't add any new items

![Screenshot (27)](https://github.com/jack-richards/bptf-autopricer/assets/16272383/93fae3ec-83ce-403d-aced-d7cdccad1bd1)

**Comment by jack-richards** [comment]
The autopricer uses prices.tf as a baseline to compare its generated prices to. So, when prices.tf is down it leads to the issue you see here. As long as the autopricer uses prices.tf as a baseline it will continue to have this issue whenever prices.tf experiences problems.
